### PR TITLE
Allow keyboard shortcuts

### PR DESCRIPTION
**Pull request by patkujawa-wf**
image

### CODE REVIEW

**Comment by georgelesica-wf** [comment]
Can we do one for the create ticket command, just for symmetry?

**Comment by patkujawa-wf** [comment]
Never!

**Comment by patkujawa-wf** [comment]
Well that didn't work:
image

**Comment by patkujawa-wf** [comment]
@georgelesica-wf ready for merge

**Comment by patkujawa-wf** [comment]
Weird, I seem to always have to do the shortcut twice. I wonder if it has to do with the background scripts usage, or maybe dart to js?

**Pull request merged**
