### PR TITLE
Add support for new deploy functionality

### PR DESCRIPTION
**Pull request by charliekump-wf**
@georgelesica-wf @patkujawa-wf @todbachman-wf 

This functionality depends on https://github.com/Workiva/benderbot/pull/195

### CODE REVIEW

**Comment by georgelesica-wf** [comment]
@patkujawa-wf you wanna +10 this?

**Comment by patkujawa-wf** [comment]
@charliekump-wf is https://github.com/Workiva/benderbot/pull/195 deployed?

**Comment by patkujawa-wf** [comment]
+10
Well, it doesn't matter, the commands will be sent whether bender supports them or not.
image
image

**Comment by patkujawa-wf** [comment]
Actually, I don't like that the value of the service in the textbox is retained, because what if you work between a lot of different repos? It'd be better if we had a lookup of service name that was keyed by fork/repo. :man_shrugging:

**Comment by georgelesica-wf** [comment]
@charliekump-wf you want to address Pat's comment or just go ahead and merge and fix it later?

**Comment by patkujawa-wf** [comment]
Merge it merge it merge it

**Pull request merged**
