### PR TITLE
Add MORE commands

### PR DESCRIPTION
**Pull request by charliekump-wf**
Summary:
————-
Add more hooks into Bender

Testing:
————-
- [ ] Test 'Run Pub Get'
- [ ] Test 'Run SDK Bootstrap'
- [ ] Test 'Update Dart Dependencies'

FYI: @josephswanson-wf @chrisgustavsen-wf @jayudey-wf @georgelesica-wf @patkujawa-wf @todbachman-wf

### CODE REVIEW

**Comment by charliekump-wf** [comment]
Not yet deployed, after tonight it will be.

**Comment by todbachman-wf** [comment]
Out of curiosity, what does the `Run Pub Get` option do for you?

**Comment by charliekump-wf** [comment]
@todbachman-wf Mostly for updating pubspec.lock files.

**Comment by todbachman-wf** [comment]
But  `pub get` won't update a lock file, right? You have to do a pub upgrade for that, don't you?

**Comment by charliekump-wf** [comment]
By mostly, I mean that is the one use case haha

**Comment by charliekump-wf** [comment]
@todbachman-wf If you've updated the pubspec.yaml and did not commit lock changes. It's a thing people do apparently...

**Comment by charliekump-wf** [comment]
It's definitely not crucial

**Comment by patkujawa-wf** [comment]
It's a handy command, too, if you use github to create a PR by updating the yaml file, then you can use bender to update the lockfile to the correct hash or version or whatnot.

**Comment by patkujawa-wf** [comment]
@georgelesica-wf released into the app store?

**Comment by josephswanson-wf** [comment]
jjylvhw7fw

It is there for sure.. still not certain how we are supposed to handle our deps for dart services though @patkujawa-wf so punting on the +10

**Pull request merged**
